<a href="https://colab.research.google.com/github/ErangaOttachchige/PyTorch-101/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [29]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [30]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [31]:
scalar.ndim

0

In [32]:
# Get tensor back as Python int
scalar.item()

7

In [33]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [34]:
vector.ndim

1

In [35]:
vector.shape

torch.Size([2])

In [36]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [37]:
MATRIX.ndim

2

In [38]:
MATRIX[0]

tensor([7, 8])

In [39]:
MATRIX[1]

tensor([ 9, 10])

In [40]:
MATRIX.shape

torch.Size([2, 2])

In [41]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [42]:
TENSOR.ndim

3

In [43]:
TENSOR.shape

torch.Size([1, 3, 3])

In [44]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [45]:
TENSOR[0][1]

tensor([3, 6, 9])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `

Torch random tensors: https://docs.pytorch.org/docs/stable/generated/torch.rand.html


In [49]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4014, 0.7066, 0.3878, 0.8226],
        [0.3869, 0.7047, 0.3298, 0.1925],
        [0.5628, 0.4930, 0.5959, 0.4440]])

In [50]:
random_tensor.ndim

2

In [53]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)